### ISSUE TITLE
Add button animations (ripple) in RectangularButton

### ISSUE THREAD

**Issue by Driexus** [Driexus/SimpleMoneyTracker#3]
The button should turn grey-ish when touched and then turn back to its original color when it is let go.
This is the basic behavior one would expect any button to have.
The color variable tied to the money activity color should not be changed in this process.

These might be useful:
- https://docs.flutter.dev/release/breaking-changes/buttons
- https://stackoverflow.com/questions/60414398/custom-button-in-flutter

**Comment by Driexus** [comment]
This is probably the reason:
https://stackoverflow.com/questions/45424621/inkwell-not-showing-ripple-effect

**Comment by master-wayne7** [comment]
You can wrap your widget with inkwell. If it still not showing ripple effect then wrap that inkwell with Material widget.

**Comment by Driexus** [comment]
Thank you, this is the fix i used in other buttons too. 
I have a new problem now though. There is quite a big delay before the ripple effect starts. This might be due to the fact that everything resides inside a TabBar. Do you know how I can decrease the starting ripple duration or increase the ripple animation speed?
